services:
  sniff_core:
    build: .
    container_name: sniff_laptop
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - ../../ros2_ws:/ros2_ws
      - /dev:/dev
    command: /bin/bash
    tty: true
    stdin_open: true